include "../targets/survivor.inc"
survivor(name "survivor1" pose [ 3.92 0.08 0.0 -74 ] fiducial_return 101)
survivor(name "survivor2" pose [ 2.48 -1.28 0.0 -123 ] fiducial_return 102)
survivor(name "survivor3" pose [ -1.28 -2.80 0.0 -156 ] fiducial_return 103)
survivor(name "survivor4" pose [ -3.76 3.44 0.0 29 ] fiducial_return 104)
survivor(name "survivor5" pose [ -3.52 -3.28 0.0 23 ] fiducial_return 105)
survivor(name "survivor6" pose [ 0.96 3.04 0.0 -61 ] fiducial_return 106)
survivor(name "survivor7" pose [ 0.40 -2.48 0.0 64 ] fiducial_return 107)
