
include "../targets/survivor.inc"
survivor(name "survivor1" pose [ -2.96 -0.48 0.0 21 ] fiducial_return 101)
survivor(name "survivor2" pose [ 3.28 -1.60 0.0 -154 ] fiducial_return 102)
survivor(name "survivor3" pose [ -3.76 -2.48 0.0 -39 ] fiducial_return 103)
survivor(name "survivor4" pose [ -1.20 2.88 0.0 14 ] fiducial_return 104)
survivor(name "survivor5" pose [ -2.16 -0.30 0.0 87 ] fiducial_return 105)
